version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: blackmatte_db
    environment:
      POSTGRES_USER: superadmin # User có quyền cao nhất (Admin DBA)
      POSTGRES_PASSWORD: superadmin_password
      POSTGRES_DB: blackmatte_db
    ports:
      - "5432:5432"
    volumes:
      # Mount thư mục ./database-init vào /docker-entrypoint-initdb.d
      # Docker engine sẽ tự động chạy file .sql bên trong khi DB rỗng lúc mới start
      - ./database-init:/docker-entrypoint-initdb.d
      # Volume để lưu trữ data postgres tránh mất mát khi restart container
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
