import { UserRow } from '@/types/user'
import { NextResponse } from 'next/server'

export async function GET() {
    const data: UserRow[] = [
        {
            id: 1,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Hoạt động',
        },
        {
            id: 2,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Hoạt động',
        },
        {
            id: 3,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Hoạt động',
        },
        {
            id: 4,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Hoạt động',
        },
        {
            id: 5,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Hoạt động',
        },
        {
            id: 6,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 7,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 8,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 9,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 10,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 11,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 12,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 13,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 14,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 15,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 16,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 17,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 18,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 19,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Khóa',
        },
        {
            id: 20,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Chờ kích hoạt',
        },
        {
            id: 21,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Chờ kích hoạt',
        },
        {
            id: 22,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Chờ kích hoạt',
        },
        {
            id: 23,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Chờ kích hoạt',
        },
        {
            id: 24,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Chờ kích hoạt',
        },
        {
            id: 25,
            user: 'username',
            fullName: 'Nguyễn Văn A',
            email: 'abc@vnpay.vn',
            tel: '0123456789',
            role: 'Quản trị viên',
            status: 'Chờ kích hoạt',
        },
    ].map((item, index) => ({ ...item, index: index + 1 }))

    return NextResponse.json(data)
}
