spring:
  profiles:
    active: ${ENV:dev}

  datasource:
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    encoding: UTF-8
    placeholder-replacement: false
    out-of-order: false
    mixed: false

logging:
  level:
    org.flywaydb: INFO
    org.springframework: INFO
    com.blackmatte: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"