spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

    connect-retries: 5
    connect-retries-interval: 180
    lock-retry-count: 100

    validate-on-migrate: true
    clean-disabled: true