spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/blackmatte_blog}
    username: ${DB_USER:blackmatte_admin}
    password: ${DB_PASSWORD:AdminBlackmatte@2024}

  flyway:
    output-query-results: true
    connect-retries: 2
    connect-retries-interval: 60

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework: DEBUG