spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/blackmatte_blog}
    username: ${DB_USER:blackmatte_admin}
    password: ${DB_PASSWORD:AdminBlackmatte@2024}
    driver-class-name: org.postgresql.Driver
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    connect-retries: 2
    connect-retries-interval: 60

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework: DEBUG
    com.blackmatte: DEBUG
    org.postgresql: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
debug: true