spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  flyway:
    output-query-results: false
    connect-retries: 5
    connect-retries-interval: 180
    lock-retry-count: 100